{% set name = "print-on-steroids" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/print-on-steroids-{{ version }}.tar.gz
  sha256: 3d2027511c6cd68e3ed808b34270bfc2141bdfbf697dccc14248a60e0037aef5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - rich
    - tqdm

test:
  imports:
    - print_on_steroids
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/konstantinjdobler/print-on-steroids
  summary: A lean and hackable rich logger and print function.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - konstantinjdobler
